spring:
  liquibase:
    change-log: installers/flowable/schema/schema.xml
    enabled: true
  flyway:
    enabled: false
  datasource:
    username: snl
    password: snl
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/flowable?stringtype=unspecified
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
flowable:
  database-table-prefix: flw
  eventregistry:
    enabled: true
  databaseSchemaUpdate: true

server:
  port: 9080
