spring:
  liquibase:
    change-log: installers/flowable/schema/schema.xml
    enabled: true
  flyway:
    enabled: false
  datasource:
    username: lamis
    password: lamis
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/flowable?stringtype=unspecified
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
flowable:
  eventregistry:
    enabled: true
  databaseSchemaUpdate: true
  database-schema: act

server:
  port: 9080
